### ISSUE TITLE
"EasyHook32.dll"須改為"EasyHook32d.ddl"64位才有效

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Prcuvu/ezgdi#17]
```
RT，應該是注冊表里的文件名多了個字母"d"。64位windows7英文��
�艦版測試有效，謝謝你（們）了！
```

Original issue reported on code.google.com by `yet...@gmail.com` on 18 Oct 2010 at 9:09

**Comment by Prcuvu** [comment]
This issue can be closed since ezgdi can be recompiled to avoid the problem.
