### ISSUE TITLE
ezgdi-x86.dll linked to EasyHook32d.dll not EasyHook32.dll

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Prcuvu/ezgdi#20]
```
What version of the product are you using? On what operating system?
ezgdi-r87 on windows 7 x64 Home Premium


```

Original issue reported on code.google.com by `AYermak...@gmail.com` on 7 Jan 2011 at 3:05

**Comment by Prcuvu** [comment]
This issue can be closed since ezgdi can be recompiled to avoid the problem.
